dist: xenial
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
before_install:
  - sudo apt-get update
  - sudo apt-get install libgit2-24
install:
  - pip install . pytest pytest-cov coverage codacy-coverage --upgrade
script: make travisbuild
