dist: xenial
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
install:
  - pip install . pytest pytest-cov coverage codacy-coverage --upgrade
script: make travisbuild
